### ISSUE TITLE
Office激活脚本中两个连续的cd导致只适用于x86版本

### ISSUE THREAD

**Issue by jojo59516** [Mogeko/KMS#1]
`cd /d %ProgramFiles%\Microsoft Office\Office16
cd /d %ProgramFiles(x86)%\Microsoft Office\Office16`
实际使用中如果是x64版本需要注释掉第二个cd才能正常工作。

另外建议末尾增加个“按任意键退出”给个看结果的机会。。。

**Comment by Mogeko** [comment]
对于 x64 版本的 office 来说， ` cd /d %ProgramFiles(x86)%\Microsoft Office\Office16` 是一道错误的命令。因为如果使用 x64 版本的 office，应该是不存在 `%ProgramFiles(x86)%\Microsoft Office\Office16` 这个目录的，就算就算执行这个命令，工作目录依然是 `%ProgramFiles%\Microsoft Office\Office16`。

**Comment by mogeko** [comment]
这么写主要是为了照顾安装 64 位系统 + 32 位 Office 的的用户。没想到 64 位的 Office 也会动 `%ProgramFiles(x86)%\Microsoft Office\Office16`，是我想得太简单了。换了个找 `ospp.vbs` 的方法，应该能正常工作了。

关于第二个问题。我的想法是：既然没有比「打开 Office」更好的方法查看是否激活成功，那么在脚本执行完后 `pause` 就显得有点多余。  
我增加了一个 `/Office_Activate/查看 Office 状态.cmd` 脚本来查看 Office 的状态。
