### ISSUE TITLE
在win10中cmd中会出现C:/program拓展名无效的问题

### ISSUE THREAD

**Issue by lixiandea** [Mogeko/KMS#2]
cmd中会使用空格作为控制，室用ospp作为变量名代替会导致错误，应该使用带引号的路径作为ospp的值，只有我一个人有这个问题吗

**Comment by TudoRex** [comment]
我也有这个问题， win10家庭版

**Comment by lixiandea** [comment]
将其中的变量%ospp%修改为ospp路径就可以了，其中路径需要带引号

**Comment by mogeko** [comment]
都怪我偷懒，加上入了 Office 365，所以上一个版本的脚本没有测试过就提交了，才犯了这么基本的错误\_(:з」∠)\_这次专门开了虚拟机装了 Office 来测试，应该没有问题了。

解决方法就像 @lixiandea 说的那样，给 `%ospp%` 加一对引号就可以了。

**Comment by GoogleBeEvil** [comment]
嘛，你是不是只考虑了安装在C盘的情况，加了引号，若在D盘还是会无效，虽然，手改下路径就解决的了

**Comment by mogeko** [comment]
现在可以自定义 `ospp.vbs` 文件的位置了 https://github.com/Mogeko/kms/commit/78c8897a1f0be5575829a62ecc9e505394dc7666

不管 Office 安装在哪个盘，只要提供正确的 `ospp.vbs` 位置都可以用了

~~目前还要两个功能要添加，所以还没有合到 `master` 分支上~~
